version: "3"

services:
  openresty:
    build:
      context: ./openresty
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./rootfs:/root
      - ./volumes/openresty/etc/nginx/conf.d:/etc/nginx/conf.d
  
  redis:
    image: docker.io/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./rootfs:/root
      - ./volumes/redis/data:/data
      # - ./volumes/redis/etc/redis.conf:/usr/local/etc/redis/redis.conf

  